### ISSUE TITLE
加载Viewpager时，报错类型转换异常。

### ISSUE THREAD

**Issue by carozhu** [q876625596/GenjiDialogV2#2]
求解，问题如下：
java.lang.ClassCastException: com.ly.genjidialog.GenjiDialog cannot be cast to com.package.MyFragment.
 
你这Dialog封装的蛮不错。

**Comment by carozhu** [comment]
没找到原因是在哪里出的问题。

**Comment by q876625596** [comment]
可以贴一下代码吗？

**Comment by carozhu** [comment]
comonSettingDialog = newGenjiDialog((dialogOptions, genjiDialog) -> {
            dialogOptions.setLayoutId(R.layout.menu_common_setting);
            dialogOptions.setWidth(ScreenUtils.Companion.getScreenWidth(context));
            dialogOptions.setHeight(ScreenUtils.Companion.getScreenHiegt(context)/2);
            dialogOptions.setUnLeak(true);
            convertListenerFun(dialogOptions, (viewHolder, genjiDialogConvert) -> {
                LinearLayout statusView = viewHolder.getView(R.id.status_view);
                int statusBarHeight = DisplayHelper.getStatusBarHeight(context);
                ViewGroup.LayoutParams params = statusView.getLayoutParams();
                if (params instanceof ConstraintLayout.LayoutParams) {
                    statusView.setLayoutParams(new ConstraintLayout.LayoutParams(ConstraintLayout.LayoutParams.MATCH_PARENT, statusBarHeight));
                }
                else if (params instanceof LinearLayout.LayoutParams){
                    statusView.setLayoutParams(new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, statusBarHeight));
                }
                //InLoadData
                viewPager = viewHolder.getView(R.id.viewPager);
                mTab = viewHolder.getView(R.id.mTab);
                chhildragmentManager = genjiDialogConvert.getChildFragment();


                List<Fragment> fragmentList = new ArrayList<>();
                fragmentList.add(VideoCommSettingFragment.newInstance());
                fragmentList.add(PhotoCommSettingFragment.newInstance());

                ViewpagerAdapter viewpagerAdapter = new ViewpagerAdapter(chhildragmentManager,fragmentList);

                viewPager.setAdapter(viewpagerAdapter);

                viewPager.setOffscreenPageLimit(2);
                viewPager.setCurrentItem(0);
                viewPager.setScrollble(false);


                NavigationController navigationController = mTab.custom()
                        .addItem(newItem(context,R.drawable.ic_framing_video_setting_off,R.drawable.ic_framing_video_setting_on))
                        .addItem(newItem(context,R.drawable.ic_framing_general_setting_off,R.drawable.ic_framing_general_setting_on))
                        .enableAnimateLayoutChanges()
                        .build();
                navigationController.setupWithViewPager(viewPager);
                return null;
            });
            return null;
        });

**Comment by carozhu** [comment]
调用这一句就报错：
viewPager.setAdapter(viewpagerAdapter);

**Comment by q876625596** [comment]
ViewpagerAdapter viewpagerAdapter = new ViewpagerAdapter(chhildragmentManager,fragmentList);
把这里的chhildragmentManager换成GenjiDialog对象的chhildragmentManager试试

**Comment by q876625596** [comment]
因为你的viewPager是属于DialogFragment里面的，所以需要用dialogfragment的fragmentmanager

**Comment by carozhu** [comment]
我就是这么做的：
   open fun getChildFragment():FragmentManager{

        return childFragmentManager
    }
我在GenjiDialog里面加了这方法

**Comment by q876625596** [comment]
我模拟了一下，在fragment里面弹出dialog，然后这个dialog里面是一个viewPager+fragment的情况，我这边并没有崩溃，dialog配置代码如下，方便的话，能否将你的这部分完整代码上传到github，我去clone之后解决一下
``` kotlin
val dialog = newGenjiDialog {
            layoutId = R.layout.dialog_pager
            gravity = DialogGravity.LEFT_CENTER
            isFullVerticalOverStatusBar = true
            unLeak = true
            width = 300.toPx()
            convertListenerFun { holder, dialog ->
                val list = mutableListOf<Fragment>()
                list.add(AAAFragment())
                list.add(AAAFragment())
                list.add(AAAFragment())
                val pager = holder.getView<ViewPager>(R.id.viewPager)!!
                pager.adapter = AAAViewPagerAdapter(dialog.childFragmentManager, list)
            }
        }
        btn.setOnClickListener {
            dialog.showOnWindow(childFragmentManager)
        }
```

**Comment by carozhu** [comment]
解决了,是我的BaseFragment搞的鬼。粗心了.尴尬.
我的BaseFragment里面有取parent fragment，结果肯定是转换异常。
。。。。
抱歉，让你费心啦。

**Comment by carozhu** [comment]
再次点赞。库设计的很好，学习了。
